<?php

namespace General\MoviedbBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function getMovies()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->OrderBy('m.title', 'ASC')
            ->OrderBy('m.genre', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

}
